# Generated by Django 2.1.7 on 2019-02-19 05:02

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('i_d', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_adminkvm', models.BooleanField(default=False)),
                ('token_id', models.CharField(max_length=255, null=True)),
                ('token_expired', models.DateTimeField(null=True)),
                ('money', models.CharField(default='0', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subnets_associated', models.CharField(max_length=255)),
                ('shared', models.IntegerField()),
                ('external', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('admin_state_up', models.IntegerField()),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='superadmin.MyUser')),
            ],
            options={
                'db_table': 'client_networks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField()),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='superadmin.MyUser')),
            ],
            options={
                'db_table': 'oders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('project', models.CharField(max_length=255)),
                ('userdomain', models.CharField(max_length=255)),
                ('projectdomain', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ops',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('ram', models.IntegerField()),
                ('vcpus', models.IntegerField()),
                ('disk', models.IntegerField()),
                ('created', models.CharField(max_length=255, null=True)),
                ('i_d', models.CharField(max_length=255, null=True)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='superadmin.MyUser')),
            ],
            options={
                'db_table': 'serverVM',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('i_d', models.CharField(max_length=255)),
                ('ops', models.ForeignKey(db_column='ops', on_delete=django.db.models.deletion.CASCADE, to='superadmin.Ops')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='superadmin.MyUser')),
            ],
            options={
                'db_table': 'snapshot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sshkeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ops', models.ForeignKey(db_column='ops', on_delete=django.db.models.deletion.CASCADE, to='superadmin.Ops')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to='superadmin.MyUser')),
            ],
            options={
                'db_table': 'sshkeys',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='images',
            name='ops',
            field=models.ForeignKey(db_column='ops', on_delete=django.db.models.deletion.CASCADE, to='superadmin.Ops'),
        ),
    ]
