# Generated by Django 2.1.7 on 2019-02-25 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={},
        ),
        migrations.AlterModelOptions(
            name='networks',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ops',
            options={},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={},
        ),
        migrations.AlterModelOptions(
            name='snapshot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sshkeys',
            options={},
        ),
        migrations.AddField(
            model_name='myuser',
            name='address1',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='address2',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='addressRegister',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='company',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='director',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='postCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='taxID',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='myuser',
            name='timezone',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='images',
            name='ops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.Ops'),
        ),
        migrations.AlterField(
            model_name='networks',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oders',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='ops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.Ops'),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sshkeys',
            name='ops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.Ops'),
        ),
        migrations.AlterField(
            model_name='sshkeys',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
