# Generated by Django 2.1.7 on 2019-02-25 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20190225_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='myuser',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
