# Generated by Django 2.1.7 on 2019-02-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_auto_20190225_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
