# Generated by Django 2.1.7 on 2019-02-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_auto_20190226_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField(default=50000)),
                ('vcpus', models.IntegerField(default=60000)),
                ('disk_hdd', models.IntegerField(default=3000)),
                ('disk_ssd', models.IntegerField(default=5000)),
            ],
        ),
    ]
