# Generated by Django 2.1.7 on 2019-02-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_auto_20190226_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ops',
            name='disk_hdd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ops',
            name='disk_ssd',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
