# Generated by Django 2.1.7 on 2019-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_auto_20190226_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='data_center',
            field=models.CharField(default='Hà Nội', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='os_name',
            field=models.CharField(default='Ubuntu 16.04', max_length=50),
            preserve_default=False,
        ),
    ]
