# Generated by Django 2.1.7 on 2019-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_auto_20190226_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='ops',
            name='net_provider',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
