# Generated by Django 2.1.7 on 2019-03-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_auto_20190227_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oders',
            name='ip',
        ),
        migrations.AddField(
            model_name='oders',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='oders',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
