# Generated by Django 2.1.7 on 2019-03-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_auto_20190307_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='pay_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
